### ISSUE TITLE
go_1_18: .Could not build package

### ISSUE THREAD

**Issue by ejunker** [benchkram/bob-quick-start#6]
I'm excited to try bob but running into some issues. I'm running this on a Debian VM running on an M3 Macbook Pro. 

```
$ bob --version
bob version 0.8.2 linux/arm64
```

```
$ nix --version
nix (Nix) 2.21.0
```

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

```
$ bob build --verbosity 10
Computed hash [h: ec8ab94e545957bb] for task [t: build], using [inputs:0] input files 
resolving build/server
Building nix dependencies. This may take a while...
go_1_18: .Could not build package
```

I know it has something to do with Nix but I have never used Nix before.

**Comment by Equanox** [comment]
The go_1_18 package is not inclueded in nixpkgs-unstable (search for packages [here](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=go_)). Try to use just use `go` instead of `go_1_18`

Will update the docs accordingly.

**Comment by ejunker** [comment]
I searched for packages and see `go_1_22` and I tried that but got a similar error. `go_1_22: .Could not build package`. The error message is not very descriptive. It might only be an issue on my machine. Feel free to close the issue.

Update: I tried using `nix-shell` and that failed so then I eventually saw that on Debian systems you may need to run:
```
sudo systemctl enable nix-daemon
sudo systemctl start nix-daemon
```

Once I did that I was able to run `bob build` successfully.
